CC=clang
LD=clang
RM=rm -f
CFLAGS=-c
LDFLAGS=
LIBS=-lm
.PHONY: all clean packets
all: writepackets readpackets writeDDSpackets readDDSpackets strip_prefix 

readpackets.o: readpackets.c packets.h
	$(CC) $(CFLAGS) $<

readpackets: readpackets.o
	$(LD) $< -o $@ $(LDFLAGS) $(LIBS)

writepackets.o: writepackets.c packets.h
	$(CC) $(CFLAGS) $<

writepackets: writepackets.o
	$(LD) $< -o $@ $(LDFLAGS) $(LIBS)
readDDSpackets.o: readDDSpackets.c packets.h
	$(CC) $(CFLAGS) $<

readDDSpackets: readDDSpackets.o
	$(LD) $< -o $@ $(LDFLAGS) $(LIBS)

writeDDSpackets.o: writeDDSpackets.c packets.h
	$(CC) $(CFLAGS) $<

writeDDSpackets: writeDDSpackets.o
	$(LD) $< -o $@ $(LDFLAGS) $(LIBS)

strip_prefix.o: strip_prefix.c packets.h
	$(CC) $(CFLAGS) $<

strip_prefix: strip_prefix.o
	$(LD) $< -o $@

packets: packets.ccsds

packets.ccsds:
	./writepackets <<< "3"
clean:
	$(RM) *.o writepackets readpackets readDDSpackets writeDDSpackets packets.ccsds *.log
