CC=clang
LD=clang
RM=rm -f
CFLAGS=-c
LDFLAGS=
LIBS=-lm
.PHONY: all clean packets
all: writepackets readpackets writeDDSpackets readDDSpackets strip_prefix countpackets countDDSpackets

packets.o: packets.c packets.h
	$(CC) $(CFLAGS) $<

readpackets.o: readpackets.c packets.h
	$(CC) $(CFLAGS) $<

readpackets: readpackets.o packets.o
	$(LD) $^ -o $@ $(LDFLAGS) $(LIBS)

writepackets.o: writepackets.c packets.h
	$(CC) $(CFLAGS) $<

writepackets: writepackets.o packets.o
	$(LD) $^ -o $@ $(LDFLAGS) $(LIBS)

readDDSpackets.o: readDDSpackets.c packets.h
	$(CC) $(CFLAGS) $<

readDDSpackets: readDDSpackets.o packets.o
	$(LD) $^ -o $@ $(LDFLAGS) $(LIBS)

writeDDSpackets.o: writeDDSpackets.c packets.h
	$(CC) $(CFLAGS) $<

writeDDSpackets: writeDDSpackets.o packets.o
	$(LD) $^ -o $@ $(LDFLAGS) $(LIBS)

strip_prefix.o: strip_prefix.c packets.h
	$(CC) $(CFLAGS) $<

strip_prefix: strip_prefix.o packets.o
	$(LD) $^ -o $@

countpackets.o: countpackets.c packets.h
	$(CC) $(CFLAGS) $<

countpackets: countpackets.o packets.o
	$(LD) $^ -o $@

countDDSpackets.o: countDDSpackets.c packets.h
        $(CC) $(CFLAGS) $<

countDDSpackets: countDDSpackets.o packets.o
        $(LD) $^ -o $@ $(LDFLAGS) $(LIBS)

packets: packets.ccsds

packets.ccsds:
	./writepackets <<< "3"
clean:
	$(RM) *.o writepackets readpackets readDDSpackets writeDDSpackets strip_prefix countpackets countDDSpackets  packets.ccsds *.log
